[package]
name = "rs_metis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.29.1", features = ["mint"] }
log = "0.4.22"
rs_foundation = { path = "../rs_foundation" }

[build-dependencies]
bindgen = "0.70.1"
