[package]
name = "rs_metis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22.0"
log = "0.4.17"
rs_foundation = { version = "0.1.0", path = "../rs_foundation" }

[build-dependencies]
bindgen = "0.65.1"