[package]
name = "rs_metis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.29.2", features = ["mint"] }
serde = { version = "1.0.217", features = ["derive", "rc"] }
rapier3d = { version = "0.22.0", features = ["simd-stable", "serde-serialize"] }
log = "0.4.22"
rs_foundation = { path = "../rs_foundation" }
rs_core_minimal = { path = "../rs_core_minimal" }

[build-dependencies]
bindgen = "0.71.1"
