[package]
name = "rs_v8_binding_api_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
rs_v8_host = { path = "../../rs_v8_host" }
rs_engine_v8_binding_api = { path = "../../build/target/generated/v8_binding_api/rs_engine" }
