[package]
name = "rs_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
env_logger = "0.10.0"
russimp = { version = "=2.0.5", features = ["prebuilt"] }
serde = { version = "1.0.193", features = ["derive"] }
bincode = { version = "1.3.3" }
glam = { version = "0.22.0" }
uuid = { version = "1.6.1", features = ["v4", "fast-rng", "macro-diagnostics", "serde"] }
url = { version = "2.5.0", features = ["serde"]}
rs_render = { version = "0.1.0", path = "../rs_render" }
rs_foundation = { version = "0.1.0", path = "../rs_foundation" }
rs_artifact = { version = "0.1.0", path = "../rs_artifact" }
rs_engine = { version = "0.1.0", path = "../rs_engine" }
