[package]
name = "rs_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["editor"]
renderdoc = ["rs_render/renderdoc", "rs_engine/renderdoc"]
editor = [
    "rs_shader_compiler/editor",
    "rs_render/editor",
    "rs_core_minimal/editor",
    "rs_engine/editor",
]
standalone = [
    "rs_shader_compiler/standalone",
    "rs_render/standalone",
    "rs_core_minimal/standalone",
    "rs_engine/standalone",
]

[dependencies]
egui-snarl = { git = "https://github.com/zakarumych/egui-snarl.git", rev = "0106647", version = "0.3.0", features = [
    "serde",
] }
syn = { version = "2.0.57", features = ["full", "extra-traits"] }
log = "0.4.17"
env_logger = "0.10.0"
russimp = { version = "3.2.0", features = ["prebuilt", "static-link"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.111"
bincode = { version = "1.3.3" }
glam = { version = "0.27.0", features = ["mint"] }
uuid = { version = "1.6.1", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
    "serde",
] }
url = { version = "2.5.0", features = ["serde"] }
percent-encoding = "2.3.1"
winit = { version = "0.29.4" }
egui = { version = "0.27.2" }
egui_extras = { version = "0.27.2", features = ["all_loaders"] }
egui-winit = { version = "0.27.2" }
rfd = "0.12.1"
image = "0.24.5"
regex = "1.10.2"
notify = "5.1.0"
notify-debouncer-mini = { version = "0.2.0" }
walkdir = "2"
dunce = "1.0.4"
path-slash = "0.1.4"
md-5 = { version = "0.10.6" }
anyhow = { version = "1.0.79" }
lazy_static = "1.4.0"
image_dds = { version = "0.5.0" }
clap = { version = "4.5.4", features = ["derive"] }
naga = { version = "0.19.0" }
wgpu = "0.19.1"
rand = { version = "0.8.5" }
mp4 = { version = "0.14.0" }
transform-gizmo-egui = { path = "../.xmake/deps/egui-gizmo/crates/transform-gizmo-egui" }
rs_render = { path = "../rs_render" }
rs_foundation = { path = "../rs_foundation" }
rs_artifact = { path = "../rs_artifact" }
rs_engine = { path = "../rs_engine" }
rs_hotreload_plugin = { path = "../rs_hotreload_plugin" }
rs_shader_compiler = { path = "../rs_shader_compiler" }
rs_core_minimal = { path = "../rs_core_minimal" }
rs_assimp = { path = "../rs_assimp" }
rs_proc_macros = { path = "../rs_proc_macros" }
rs_metis = { path = "../rs_metis" }
rs_media = { path = "../rs_media" }
rs_audio = { path = "../rs_audio" }
