use strum_macros::EnumIter;

#[cfg(feature = "editor")]
pub mod env;
pub mod error;

#[allow(non_camel_case_types)]
#[derive(EnumIter, Debug, Clone, Copy, PartialEq, Eq)]
pub enum TextureFormatType {
    ARGB_8888,
    ARGB_16F,
    ARGB_32F,
    RGBA_1010102,
    ATC_RGB,
    ATC_RGBA_Explicit,
    ATC_RGBA_Interpolated,
    ATI1N,
    ATI2N,
    ATI2N_XY,
    ATI2N_DXT5,
    BC1,
    BC2,
    BC3,
    BC4,
    BC4_S,
    BC5,
    BC5_S,
    BC6H,
    BC7,
    DXT1,
    DXT3,
    DXT5,
    DXT5_xGBR,
    DXT5_RxBG,
    DXT5_RBxG,
    DXT5_xRBG,
    DXT5_RGxB,
    DXT5_xGxR,
    ETC_RGB,
    ETC2_RGB,
    ETC2_RGBA,
    ETC2_RGBA1,
    BRLG,
    ASTC_4x4_ldr,
    ASTC_5x4_ldr,
    ASTC_5x5_ldr,
    ASTC_6x5_ldr,
    ASTC_6x6_ldr,
    ASTC_8x5_ldr,
    ASTC_8x6_ldr,
    ASTC_8x8_ldr,
    ASTC_10x5_ldr,
    ASTC_10x6_ldr,
    ASTC_10x8_ldr,
    ASTC_10x10_ldr,
    ASTC_12x10_ldr,
    ASTC_12x12_ldr,
    ASTC_4x4_hdr,
    ASTC_5x4_hdr,
    ASTC_5x5_hdr,
    ASTC_6x5_hdr,
    ASTC_6x6_hdr,
    ASTC_8x5_hdr,
    ASTC_8x6_hdr,
    ASTC_8x8_hdr,
    ASTC_10x5_hdr,
    ASTC_10x6_hdr,
    ASTC_10x8_hdr,
    ASTC_10x10_hdr,
    ASTC_12x10_hdr,
    ASTC_12x12_hdr,
}
