#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum EKeyCode {
    Backquote,
    Backslash,
    BracketLeft,
    BracketRight,
    Comma,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Equal,
    IntlBackslash,
    IntlRo,
    IntlYen,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Minus,
    Period,
    Quote,
    Semicolon,
    Slash,
    AltLeft,
    AltRight,
    Backspace,
    CapsLock,
    ContextMenu,
    ControlLeft,
    ControlRight,
    Enter,
    SuperLeft,
    SuperRight,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    Convert,
    KanaMode,
    ///
    Lang1,
    ///
    Lang2,
    Lang3,
    Lang4,
    Lang5,
    NonConvert,
    ///
    Delete,
    End,
    Help,
    Home,
    Insert,
    PageDown,
    PageUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    NumLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadBackspace,
    NumpadClear,
    NumpadClearEntry,
    NumpadComma,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadHash,
    NumpadMemoryAdd,
    NumpadMemoryClear,
    NumpadMemoryRecall,
    NumpadMemoryStore,
    NumpadMemorySubtract,
    NumpadMultiply,
    NumpadParenLeft,
    NumpadParenRight,
    NumpadStar,
    NumpadSubtract,
    Escape,
    Fn,
    FnLock,
    PrintScreen,
    ScrollLock,
    Pause,
    BrowserBack,
    BrowserFavorites,
    BrowserForward,
    BrowserHome,
    BrowserRefresh,
    BrowserSearch,
    BrowserStop,
    Eject,
    LaunchApp1,
    LaunchApp2,
    LaunchMail,
    MediaPlayPause,
    MediaSelect,
    MediaStop,
    MediaTrackNext,
    MediaTrackPrevious,
    Power,
    Sleep,
    AudioVolumeDown,
    AudioVolumeMute,
    AudioVolumeUp,
    WakeUp,
    Meta,
    Hyper,
    Turbo,
    Abort,
    Resume,
    Suspend,
    Again,
    Copy,
    Cut,
    Find,
    Open,
    Paste,
    Props,
    Select,
    Undo,
    Hiragana,
    Katakana,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,
}

impl EKeyCode {
    pub fn from_winit_key_code(key_code: winit::keyboard::KeyCode) -> EKeyCode {
        match key_code {
            winit::keyboard::KeyCode::Backquote => EKeyCode::Backquote,
            winit::keyboard::KeyCode::Backslash => EKeyCode::Backslash,
            winit::keyboard::KeyCode::BracketLeft => EKeyCode::BracketLeft,
            winit::keyboard::KeyCode::BracketRight => EKeyCode::BracketRight,
            winit::keyboard::KeyCode::Comma => EKeyCode::Comma,
            winit::keyboard::KeyCode::Digit0 => EKeyCode::Digit0,
            winit::keyboard::KeyCode::Digit1 => EKeyCode::Digit1,
            winit::keyboard::KeyCode::Digit2 => EKeyCode::Digit2,
            winit::keyboard::KeyCode::Digit3 => EKeyCode::Digit3,
            winit::keyboard::KeyCode::Digit4 => EKeyCode::Digit4,
            winit::keyboard::KeyCode::Digit5 => EKeyCode::Digit5,
            winit::keyboard::KeyCode::Digit6 => EKeyCode::Digit6,
            winit::keyboard::KeyCode::Digit7 => EKeyCode::Digit7,
            winit::keyboard::KeyCode::Digit8 => EKeyCode::Digit8,
            winit::keyboard::KeyCode::Digit9 => EKeyCode::Digit9,
            winit::keyboard::KeyCode::Equal => EKeyCode::Equal,
            winit::keyboard::KeyCode::IntlBackslash => EKeyCode::IntlBackslash,
            winit::keyboard::KeyCode::IntlRo => EKeyCode::IntlRo,
            winit::keyboard::KeyCode::IntlYen => EKeyCode::IntlYen,
            winit::keyboard::KeyCode::KeyA => EKeyCode::KeyA,
            winit::keyboard::KeyCode::KeyB => EKeyCode::KeyB,
            winit::keyboard::KeyCode::KeyC => EKeyCode::KeyC,
            winit::keyboard::KeyCode::KeyD => EKeyCode::KeyD,
            winit::keyboard::KeyCode::KeyE => EKeyCode::KeyE,
            winit::keyboard::KeyCode::KeyF => EKeyCode::KeyF,
            winit::keyboard::KeyCode::KeyG => EKeyCode::KeyG,
            winit::keyboard::KeyCode::KeyH => EKeyCode::KeyH,
            winit::keyboard::KeyCode::KeyI => EKeyCode::KeyI,
            winit::keyboard::KeyCode::KeyJ => EKeyCode::KeyJ,
            winit::keyboard::KeyCode::KeyK => EKeyCode::KeyK,
            winit::keyboard::KeyCode::KeyL => EKeyCode::KeyL,
            winit::keyboard::KeyCode::KeyM => EKeyCode::KeyM,
            winit::keyboard::KeyCode::KeyN => EKeyCode::KeyN,
            winit::keyboard::KeyCode::KeyO => EKeyCode::KeyO,
            winit::keyboard::KeyCode::KeyP => EKeyCode::KeyP,
            winit::keyboard::KeyCode::KeyQ => EKeyCode::KeyQ,
            winit::keyboard::KeyCode::KeyR => EKeyCode::KeyR,
            winit::keyboard::KeyCode::KeyS => EKeyCode::KeyS,
            winit::keyboard::KeyCode::KeyT => EKeyCode::KeyT,
            winit::keyboard::KeyCode::KeyU => EKeyCode::KeyU,
            winit::keyboard::KeyCode::KeyV => EKeyCode::KeyV,
            winit::keyboard::KeyCode::KeyW => EKeyCode::KeyW,
            winit::keyboard::KeyCode::KeyX => EKeyCode::KeyX,
            winit::keyboard::KeyCode::KeyY => EKeyCode::KeyY,
            winit::keyboard::KeyCode::KeyZ => EKeyCode::KeyZ,
            winit::keyboard::KeyCode::Minus => EKeyCode::Minus,
            winit::keyboard::KeyCode::Period => EKeyCode::Period,
            winit::keyboard::KeyCode::Quote => EKeyCode::Quote,
            winit::keyboard::KeyCode::Semicolon => EKeyCode::Semicolon,
            winit::keyboard::KeyCode::Slash => EKeyCode::Slash,
            winit::keyboard::KeyCode::AltLeft => EKeyCode::AltLeft,
            winit::keyboard::KeyCode::AltRight => EKeyCode::AltRight,
            winit::keyboard::KeyCode::Backspace => EKeyCode::Backspace,
            winit::keyboard::KeyCode::CapsLock => EKeyCode::CapsLock,
            winit::keyboard::KeyCode::ContextMenu => EKeyCode::ContextMenu,
            winit::keyboard::KeyCode::ControlLeft => EKeyCode::ControlLeft,
            winit::keyboard::KeyCode::ControlRight => EKeyCode::ControlRight,
            winit::keyboard::KeyCode::Enter => EKeyCode::Enter,
            winit::keyboard::KeyCode::SuperLeft => EKeyCode::SuperLeft,
            winit::keyboard::KeyCode::SuperRight => EKeyCode::SuperRight,
            winit::keyboard::KeyCode::ShiftLeft => EKeyCode::ShiftLeft,
            winit::keyboard::KeyCode::ShiftRight => EKeyCode::ShiftRight,
            winit::keyboard::KeyCode::Space => EKeyCode::Space,
            winit::keyboard::KeyCode::Tab => EKeyCode::Tab,
            winit::keyboard::KeyCode::Convert => EKeyCode::Convert,
            winit::keyboard::KeyCode::KanaMode => EKeyCode::KanaMode,
            winit::keyboard::KeyCode::Lang1 => EKeyCode::Lang1,
            winit::keyboard::KeyCode::Lang2 => EKeyCode::Lang2,
            winit::keyboard::KeyCode::Lang3 => EKeyCode::Lang3,
            winit::keyboard::KeyCode::Lang4 => EKeyCode::Lang4,
            winit::keyboard::KeyCode::Lang5 => EKeyCode::Lang5,
            winit::keyboard::KeyCode::NonConvert => EKeyCode::NonConvert,
            winit::keyboard::KeyCode::Delete => EKeyCode::Delete,
            winit::keyboard::KeyCode::End => EKeyCode::End,
            winit::keyboard::KeyCode::Help => EKeyCode::Help,
            winit::keyboard::KeyCode::Home => EKeyCode::Home,
            winit::keyboard::KeyCode::Insert => EKeyCode::Insert,
            winit::keyboard::KeyCode::PageDown => EKeyCode::PageDown,
            winit::keyboard::KeyCode::PageUp => EKeyCode::PageUp,
            winit::keyboard::KeyCode::ArrowDown => EKeyCode::ArrowDown,
            winit::keyboard::KeyCode::ArrowLeft => EKeyCode::ArrowLeft,
            winit::keyboard::KeyCode::ArrowRight => EKeyCode::ArrowRight,
            winit::keyboard::KeyCode::ArrowUp => EKeyCode::ArrowUp,
            winit::keyboard::KeyCode::NumLock => EKeyCode::NumLock,
            winit::keyboard::KeyCode::Numpad0 => EKeyCode::Numpad0,
            winit::keyboard::KeyCode::Numpad1 => EKeyCode::Numpad1,
            winit::keyboard::KeyCode::Numpad2 => EKeyCode::Numpad2,
            winit::keyboard::KeyCode::Numpad3 => EKeyCode::Numpad3,
            winit::keyboard::KeyCode::Numpad4 => EKeyCode::Numpad4,
            winit::keyboard::KeyCode::Numpad5 => EKeyCode::Numpad5,
            winit::keyboard::KeyCode::Numpad6 => EKeyCode::Numpad6,
            winit::keyboard::KeyCode::Numpad7 => EKeyCode::Numpad7,
            winit::keyboard::KeyCode::Numpad8 => EKeyCode::Numpad8,
            winit::keyboard::KeyCode::Numpad9 => EKeyCode::Numpad9,
            winit::keyboard::KeyCode::NumpadAdd => EKeyCode::NumpadAdd,
            winit::keyboard::KeyCode::NumpadBackspace => EKeyCode::NumpadBackspace,
            winit::keyboard::KeyCode::NumpadClear => EKeyCode::NumpadClear,
            winit::keyboard::KeyCode::NumpadClearEntry => EKeyCode::NumpadClearEntry,
            winit::keyboard::KeyCode::NumpadComma => EKeyCode::NumpadComma,
            winit::keyboard::KeyCode::NumpadDecimal => EKeyCode::NumpadDecimal,
            winit::keyboard::KeyCode::NumpadDivide => EKeyCode::NumpadDivide,
            winit::keyboard::KeyCode::NumpadEnter => EKeyCode::NumpadEnter,
            winit::keyboard::KeyCode::NumpadEqual => EKeyCode::NumpadEqual,
            winit::keyboard::KeyCode::NumpadHash => EKeyCode::NumpadHash,
            winit::keyboard::KeyCode::NumpadMemoryAdd => EKeyCode::NumpadMemoryAdd,
            winit::keyboard::KeyCode::NumpadMemoryClear => EKeyCode::NumpadMemoryClear,
            winit::keyboard::KeyCode::NumpadMemoryRecall => EKeyCode::NumpadMemoryRecall,
            winit::keyboard::KeyCode::NumpadMemoryStore => EKeyCode::NumpadMemoryStore,
            winit::keyboard::KeyCode::NumpadMemorySubtract => EKeyCode::NumpadMemorySubtract,
            winit::keyboard::KeyCode::NumpadMultiply => EKeyCode::NumpadMultiply,
            winit::keyboard::KeyCode::NumpadParenLeft => EKeyCode::NumpadParenLeft,
            winit::keyboard::KeyCode::NumpadParenRight => EKeyCode::NumpadParenRight,
            winit::keyboard::KeyCode::NumpadStar => EKeyCode::NumpadStar,
            winit::keyboard::KeyCode::NumpadSubtract => EKeyCode::NumpadSubtract,
            winit::keyboard::KeyCode::Escape => EKeyCode::Escape,
            winit::keyboard::KeyCode::Fn => EKeyCode::Fn,
            winit::keyboard::KeyCode::FnLock => EKeyCode::FnLock,
            winit::keyboard::KeyCode::PrintScreen => EKeyCode::PrintScreen,
            winit::keyboard::KeyCode::ScrollLock => EKeyCode::ScrollLock,
            winit::keyboard::KeyCode::Pause => EKeyCode::Pause,
            winit::keyboard::KeyCode::BrowserBack => EKeyCode::BrowserBack,
            winit::keyboard::KeyCode::BrowserFavorites => EKeyCode::BrowserFavorites,
            winit::keyboard::KeyCode::BrowserForward => EKeyCode::BrowserForward,
            winit::keyboard::KeyCode::BrowserHome => EKeyCode::BrowserHome,
            winit::keyboard::KeyCode::BrowserRefresh => EKeyCode::BrowserRefresh,
            winit::keyboard::KeyCode::BrowserSearch => EKeyCode::BrowserSearch,
            winit::keyboard::KeyCode::BrowserStop => EKeyCode::BrowserStop,
            winit::keyboard::KeyCode::Eject => EKeyCode::Eject,
            winit::keyboard::KeyCode::LaunchApp1 => EKeyCode::LaunchApp1,
            winit::keyboard::KeyCode::LaunchApp2 => EKeyCode::LaunchApp2,
            winit::keyboard::KeyCode::LaunchMail => EKeyCode::LaunchMail,
            winit::keyboard::KeyCode::MediaPlayPause => EKeyCode::MediaPlayPause,
            winit::keyboard::KeyCode::MediaSelect => EKeyCode::MediaSelect,
            winit::keyboard::KeyCode::MediaStop => EKeyCode::MediaStop,
            winit::keyboard::KeyCode::MediaTrackNext => EKeyCode::MediaTrackNext,
            winit::keyboard::KeyCode::MediaTrackPrevious => EKeyCode::MediaTrackPrevious,
            winit::keyboard::KeyCode::Power => EKeyCode::Power,
            winit::keyboard::KeyCode::Sleep => EKeyCode::Sleep,
            winit::keyboard::KeyCode::AudioVolumeDown => EKeyCode::AudioVolumeDown,
            winit::keyboard::KeyCode::AudioVolumeMute => EKeyCode::AudioVolumeMute,
            winit::keyboard::KeyCode::AudioVolumeUp => EKeyCode::AudioVolumeUp,
            winit::keyboard::KeyCode::WakeUp => EKeyCode::WakeUp,
            winit::keyboard::KeyCode::Meta => EKeyCode::Meta,
            winit::keyboard::KeyCode::Hyper => EKeyCode::Hyper,
            winit::keyboard::KeyCode::Turbo => EKeyCode::Turbo,
            winit::keyboard::KeyCode::Abort => EKeyCode::Abort,
            winit::keyboard::KeyCode::Resume => EKeyCode::Resume,
            winit::keyboard::KeyCode::Suspend => EKeyCode::Suspend,
            winit::keyboard::KeyCode::Again => EKeyCode::Again,
            winit::keyboard::KeyCode::Copy => EKeyCode::Copy,
            winit::keyboard::KeyCode::Cut => EKeyCode::Cut,
            winit::keyboard::KeyCode::Find => EKeyCode::Find,
            winit::keyboard::KeyCode::Open => EKeyCode::Open,
            winit::keyboard::KeyCode::Paste => EKeyCode::Paste,
            winit::keyboard::KeyCode::Props => EKeyCode::Props,
            winit::keyboard::KeyCode::Select => EKeyCode::Select,
            winit::keyboard::KeyCode::Undo => EKeyCode::Undo,
            winit::keyboard::KeyCode::Hiragana => EKeyCode::Hiragana,
            winit::keyboard::KeyCode::Katakana => EKeyCode::Katakana,
            winit::keyboard::KeyCode::F1 => EKeyCode::F1,
            winit::keyboard::KeyCode::F2 => EKeyCode::F2,
            winit::keyboard::KeyCode::F3 => EKeyCode::F3,
            winit::keyboard::KeyCode::F4 => EKeyCode::F4,
            winit::keyboard::KeyCode::F5 => EKeyCode::F5,
            winit::keyboard::KeyCode::F6 => EKeyCode::F6,
            winit::keyboard::KeyCode::F7 => EKeyCode::F7,
            winit::keyboard::KeyCode::F8 => EKeyCode::F8,
            winit::keyboard::KeyCode::F9 => EKeyCode::F9,
            winit::keyboard::KeyCode::F10 => EKeyCode::F10,
            winit::keyboard::KeyCode::F11 => EKeyCode::F11,
            winit::keyboard::KeyCode::F12 => EKeyCode::F12,
            winit::keyboard::KeyCode::F13 => EKeyCode::F13,
            winit::keyboard::KeyCode::F14 => EKeyCode::F14,
            winit::keyboard::KeyCode::F15 => EKeyCode::F15,
            winit::keyboard::KeyCode::F16 => EKeyCode::F16,
            winit::keyboard::KeyCode::F17 => EKeyCode::F17,
            winit::keyboard::KeyCode::F18 => EKeyCode::F18,
            winit::keyboard::KeyCode::F19 => EKeyCode::F19,
            winit::keyboard::KeyCode::F20 => EKeyCode::F20,
            winit::keyboard::KeyCode::F21 => EKeyCode::F21,
            winit::keyboard::KeyCode::F22 => EKeyCode::F22,
            winit::keyboard::KeyCode::F23 => EKeyCode::F23,
            winit::keyboard::KeyCode::F24 => EKeyCode::F24,
            winit::keyboard::KeyCode::F25 => EKeyCode::F25,
            winit::keyboard::KeyCode::F26 => EKeyCode::F26,
            winit::keyboard::KeyCode::F27 => EKeyCode::F27,
            winit::keyboard::KeyCode::F28 => EKeyCode::F28,
            winit::keyboard::KeyCode::F29 => EKeyCode::F29,
            winit::keyboard::KeyCode::F30 => EKeyCode::F30,
            winit::keyboard::KeyCode::F31 => EKeyCode::F31,
            winit::keyboard::KeyCode::F32 => EKeyCode::F32,
            winit::keyboard::KeyCode::F33 => EKeyCode::F33,
            winit::keyboard::KeyCode::F34 => EKeyCode::F34,
            winit::keyboard::KeyCode::F35 => EKeyCode::F35,
            _ => unreachable!(),
        }
    }
}

#[repr(C)]
#[derive(Debug)]
pub struct NativeKeyboardInput {
    pub scancode: EKeyCode,
    pub state: i32,
    pub virtual_key_code: i32,
}
