[package]
name = "rs_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["standalone"]
renderdoc = ["rs_render/renderdoc"]
editor = [
    "rs_shader_compiler/editor",
    "rs_render/editor",
    "rs_core_minimal/editor",
    "dep:anyhow",
]
standalone = [
    "rs_shader_compiler/standalone",
    "rs_render/standalone",
    "rs_core_minimal/standalone",
]
profiler = ["tracy-client/default", "rs_render/default"]
plugin_shared_crate = []

[dependencies]
bitflags = "2.6.0"
md-5 = { version = "0.10.6" }
anyhow = { version = "1.0.86", optional = true }
serde = { version = "1.0.209", features = ["derive", "rc"] }
serde_json = "1.0.127"
chrono = "0.4.38"
log = "0.4.22"
env_logger = "0.11.5"
moka = { version = "0.12.8", default-features = false, features = ["sync"] }
image = "0.25.2"
lazy_static = "1.5.0"
walkdir = "2.5.0"
rayon = "1.10.0"
egui = { version = "0.28.1" }
raw-window-handle = "0.6.2"
url = { version = "2.5.2", features = ["serde"] }
percent-encoding = "2.3.1"
wgpu = "0.20.1"
glam = { version = "0.28.0", features = ["mint", "serde"] }
uuid = { version = "1.10.0", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
    "serde",
] }
rand = { version = "0.8.5" }
tracy-client = { version = "0.17.3", default-features = false }
rapier3d = { version = "0.22.0", features = ["simd-stable"] }
rs_foundation = { path = "../rs_foundation" }
rs_audio = { path = "../rs_audio" }
rs_artifact = { path = "../rs_artifact" }
rs_render = { path = "../rs_render" }
rs_core_minimal = { path = "../rs_core_minimal" }
rs_shader_compiler = { path = "../rs_shader_compiler" }
rs_proc_macros = { path = "../rs_proc_macros" }
rs_render_types = { path = "../rs_render_types" }

[target.'cfg(not(target_os = "android"))'.dependencies]
winit = { version = "0.29.15" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.14.1"
ndk-sys = "0.5.0"
