[package]
name = "rs_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["standalone"]
renderdoc = ["rs_render/renderdoc"]
editor = [
    "rs_shader_compiler/editor",
    "rs_render/editor",
    "rs_core_minimal/editor",
    "dep:anyhow"
]
standalone = [
    "rs_shader_compiler/standalone",
    "rs_render/standalone",
    "rs_core_minimal/standalone",
]

[dependencies]
md-5 = { version = "0.10.6" }
anyhow = { version = "1.0.79", optional = true }
serde = { version = "1.0.193", features = ["derive", "rc"] }
serde_json = "1.0.111"
chrono = "0.4"
log = "0.4.17"
env_logger = "0.10.0"
moka = { version = "0.11", default-features = false, features = ["sync"] }
image = "0.24.5"
lazy_static = "1.4.0"
walkdir = "2"
rayon = "1.6"
egui = { version = "0.27.2" }
raw-window-handle = "0.6"
url = { version = "2.5.0", features = ["serde"] }
percent-encoding = "2.3.1"
wgpu = "0.19.1"
glam = { version = "0.27.0", features = ["mint", "serde"] }
uuid = { version = "1.6.1", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
    "serde",
] }
rs_foundation = { path = "../rs_foundation" }
rs_artifact = { path = "../rs_artifact" }
rs_render = { path = "../rs_render" }
rs_core_minimal = { path = "../rs_core_minimal" }
rs_shader_compiler = { path = "../rs_shader_compiler" }
rs_proc_macros = { path = "../rs_proc_macros" }

[target.'cfg(not(target_os = "android"))'.dependencies]
winit = { version = "0.29.4" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"
ndk-sys = "0.5.0"
