[package]
name = "rs_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
log = "0.4.17"
env_logger = "0.10.0"
moka = { version = "0.11", default-features = false, features = ["sync"] }
image = "0.24.5"
lazy_static = "1.4.0"
walkdir = "2"
rayon = "1.6"
egui = "0.23.0"
raw-window-handle = "0.5"
url = { version = "2.5.0", features = ["serde"]}
rs_foundation = { version = "0.1.0", path = "../rs_foundation" }
rs_artifact = { version = "0.1.0", path = "../rs_artifact" }
rs_render = { version = "0.1.0", path = "../rs_render" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"
ndk-sys = "0.5.0"
