[package]
name = "rs_desktop_standalone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["standalone"]
renderdoc = ["rs_render/renderdoc", "rs_engine/renderdoc"]
standalone = [
    "rs_render/standalone",
    "rs_engine/standalone",
    "rs_core_minimal/standalone",
]
profiler = [
    "tracy-client/default",
    "rs_render/profiler",
    "rs_engine/profiler",
]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
log = "0.4.17"
env_logger = "0.10.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.111"
bincode = { version = "1.3.3" }
glam = { version = "0.22.0" }
uuid = { version = "1.6.1", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
    "serde",
] }
url = { version = "2.5.0", features = ["serde"] }
percent-encoding = "2.3.1"
winit = { version = "0.29.4" }
egui = { version = "0.27.2" }
egui_extras = { version = "0.27.2", features = ["all_loaders"] }
egui-winit = { version = "0.27.2" }
rfd = "0.12.1"
image = "0.24.5"
regex = "1.10.2"
notify = "5.1.0"
notify-debouncer-mini = { version = "0.2.0" }
walkdir = "2"
dunce = "1.0.4"
path-slash = "0.1.4"
md-5 = { version = "0.10.6" }
anyhow = { version = "1.0.79" }
lazy_static = "1.4.0"
naga = { version = "0.19.0" }
wgpu = "0.19.1"
tracy-client = { version = "0.17.0", default-features = false }
rs_render = { version = "0.1.0", path = "../rs_render" }
rs_foundation = { version = "0.1.0", path = "../rs_foundation" }
rs_artifact = { version = "0.1.0", path = "../rs_artifact" }
rs_engine = { version = "0.1.0", path = "../rs_engine" }
rs_core_minimal = { version = "0.1.0", path = "../rs_core_minimal" }
