[package]
name = "rs_desktop_standalone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["standalone"]
renderdoc = ["rs_render/renderdoc", "rs_engine/renderdoc"]

[dependencies]
log = "0.4.17"
winit = { version = "0.29.4" }
egui = { version = "0.26.0" }
egui-winit = { version = "0.26.0" }
rs_render = { version = "0.1.0", path = "../rs_render" }
rs_foundation = { version = "0.1.0", path = "../rs_foundation" }
rs_artifact = { version = "0.1.0", path = "../rs_artifact" }
rs_engine = { version = "0.1.0", path = "../rs_engine" }