[package]
name = "rs_desktop_standalone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["standalone"]
renderdoc = ["rs_render/renderdoc", "rs_engine/renderdoc"]
standalone = [
    "rs_render/standalone",
    "rs_engine/standalone",
    "rs_core_minimal/standalone",
]
profiler = ["tracy-client/default", "rs_render/profiler", "rs_engine/profiler"]
plugin_shared_lib = ["rs_native_plugin/plugin_shared_lib"]
plugin_shared_crate = ["rs_native_plugin/plugin_shared_crate"]
plugin_dotnet = ["dep:rs_dotnet", "dep:rs_dotnet_host"]
plugin_v8 = ["dep:rs_v8_host"]

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
log = "0.4.22"
env_logger = "0.11.3"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.120"
bincode = { version = "1.3.3" }
glam = { version = "0.28.0" }
uuid = { version = "1.10.0", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
    "serde",
] }
url = { version = "2.5.2", features = ["serde"] }
percent-encoding = "2.3.1"
winit = { version = "0.29.4" }
egui = { version = "0.28.1" }
egui_extras = { version = "0.28.1", features = ["all_loaders"] }
egui-winit = { version = "0.28.1" }
rfd = "0.14.1"
image = "0.25.1"
regex = "1.10.5"
notify = "6.1.0"
notify-debouncer-mini = { version = "0.4.1" }
walkdir = "2.5.0"
dunce = "1.0.4"
path-slash = "0.2.1"
md-5 = { version = "0.10.6" }
anyhow = { version = "1.0.86" }
lazy_static = "1.5.0"
naga = { version = "0.20.0" }
wgpu = "0.20.0"
tracy-client = { version = "0.17.1", default-features = false }
rs_render = { path = "../rs_render" }
rs_foundation = { path = "../rs_foundation" }
rs_artifact = { path = "../rs_artifact" }
rs_engine = { path = "../rs_engine" }
rs_core_minimal = { path = "../rs_core_minimal" }
rs_media = { path = "../rs_media" }
rs_audio = { path = "../rs_audio" }
rs_native_plugin = { path = "../rs_native_plugin" }
rs_v8_host = { path = "../rs_v8_host", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
rs_dotnet = { path = "../rs_dotnet", optional = true }
rs_dotnet_host = { path = "../rs_dotnet_host", optional = true }