[package]
name = "rs_reflection_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
ra_ap_hir = "0.0.294"
ra_ap_ide = "0.0.294"
ra_ap_ide_assists = "0.0.294"
ra_ap_ide_db = "0.0.294"
ra_ap_load-cargo = "0.0.294"
ra_ap_project_model = "0.0.294"
ra_ap_rust-analyzer = "0.0.294"
ra_ap_vfs = "0.0.294"
ra_ap_parser = "0.0.294"
ra_ap_syntax = "0.0.294"
ra_ap_paths = "0.0.294"
ra_ap_proc_macro_api = "0.0.294"
ra_ap_salsa = "0.0.269"
ra_ap_hir_ty = "0.0.294"
proc-macro2 = "1.0.95"
syn = { version = "2.0.104", features = ["full", "extra-traits"] }
quote = "1.0.40"
prettyplease = "0.2.35"
log = "0.4.27"
env_logger = "0.11.8"
anyhow = { version = "1.0.98" }
rowan = "0.16.1"
rs_core_minimal = { path = "../../rs_core_minimal" }
