[package]
name = "rs_v8_host"
version = "0.1.0"
edition = "2021"

[dependencies]
v8 = "134.4.0"
notify = "7.0.0"
notify-debouncer-mini = { version = "0.5.0" }
walkdir = "2.5.0"
log = "0.4.22"
rs_engine = { path = "../rs_engine" }
rs_render = { path = "../rs_render" }
