[package]
name = "rs_v8_binding_api_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
ra_ap_hir = "0.0.248"
ra_ap_ide = "0.0.248"
ra_ap_ide_assists = "0.0.248"
ra_ap_ide_db = "0.0.248"
ra_ap_load-cargo = "0.0.248"
ra_ap_project_model = "0.0.248"
ra_ap_rust-analyzer = "0.0.248"
ra_ap_vfs = "0.0.248"
ra_ap_parser = "0.0.248"
ra_ap_syntax = "0.0.248"
ra_ap_paths = "0.0.248"
ra_ap_proc_macro_api = "0.0.248"
ra_ap_salsa = "0.0.250"
ra_ap_hir_ty = "0.0.248"
ra_ap_stdx = "0.0.250"
ra_ap_hir_def = "0.0.248"
proc-macro2 = "1.0.92"
syn = { version = "2.0.92", features = ["full", "extra-traits"] }
quote = "1.0.38"
prettyplease = "0.2.25"
log = "0.4.22"
env_logger = "0.11.6"
anyhow = { version = "1.0.95" }
rowan = "0.16.1"
convert_case = "0.6.0"
rs_core_minimal = { path = "../../rs_core_minimal" }
