[package]
name = "rs_build_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
log = "0.4.33"
env_logger = "0.11.11"
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
anyhow = { version = "1.0.104" }
toml_edit = "0.25.13"
glob = "0.3.4"
rs_core_minimal = { path = "../rs_core_minimal" }
rs_foundation = { path = "../rs_foundation" }
