[package]
name = "rs_android"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
env_logger = "0.10.1"
egui = "0.23.0"
url = { version = "2.5.0", features = ["serde"]}
rs_engine = { version = "0.1.0", path = "../rs_engine" }
rs_artifact = { version = "0.1.0", path = "../rs_artifact" }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21.1"
jni_fn = "0.1.2"
ndk-sys = "0.5.0"
raw-window-handle = "0.5"
rs_render = { version = "0.1.0", path = "../rs_render" }
android_logger = "0.13"
wgpu = "0.18.0"

[lib]
crate_type = ["rlib", "cdylib"]